# Generated by Django 4.2.6 on 2023-10-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("construction_est", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="construction_est.section",
                verbose_name="родительская секция",
            ),
        ),
    ]
