# Generated by Django 4.2.6 on 2023-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction_est", "0002_alter_section_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="name",
            field=models.CharField(
                default=1, max_length=50, verbose_name="название сметы"
            ),
            preserve_default=False,
        ),
    ]
