# Generated by Django 4.2.6 on 2023-10-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="наименование объекта"
                    ),
                ),
            ],
            options={
                "verbose_name": "объект строительства",
                "verbose_name_plural": "объекты строительства",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название сметы"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="construction_obj.building",
                        verbose_name="объект строительства",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="construction_obj.section",
                        verbose_name="родительская секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "секция сметы",
                "verbose_name_plural": "секции смет",
            },
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название расценки"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("work", "Работа"), ("material", "Материал")],
                        max_length=8,
                        verbose_name="тип расценки",
                    ),
                ),
                (
                    "count",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="кол-во"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="цена за единицу"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Расценка может принадлежать только той секции, у которой указан parent",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="construction_obj.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "расценка сметы",
                "verbose_name_plural": "расценки смет",
            },
        ),
    ]
